class box {
  constructor(topborder, rightborder, bottomborder, leftborder) {
    this.topborder = topborder;
    this.rightborder = rightborder;
    this.bottomborder = bottomborder;
    this.leftborder = leftborder;
  }
}

class Point {
  constructor(i, j) {
    this.i = i;
    this.j = j;
  }

  moveUp() {
    if (this.i >= 1 && game.map[this.i][this.j].topborder == false) {
      this.i -= 1;
      game.distance++;
    }
  }

  moveLeft() {
    if (this.j >= 1 && game.map[this.i][this.j].leftborder == false) {
      this.j -= 1;
      game.distance++;
    }
  }

  moveDown() {
    if (this.i <= 28 && game.map[this.i][this.j].bottomborder == false) {
      this.i += 1;
      game.distance++;
    }
    console.log(this.i)
  console.log(this.j)
  }

  moveRight() {
    if (this.j <= 28 && game.map[this.i][this.j].rightborder == false) {
      this.j += 1;
      game.distance++;
    }
  }
  
  eat(items) {
    for (let item of items) {
      if (this.i === item.i && this.j === item.j && item.isEaten == false) {
        item.isEaten = true;
        console.log(item);
        if (item.isTrap) {
          console.log(item);
          game.timer+=5;
        }
      }
    }
  }
}

class Item extends Point {
  constructor(i, j, isEaten = false) {
    super(i, j);
    this.isEaten = isEaten;
  }
}

class Trap extends Item {
  isTrap = true;
}

class Game {
  map = [
    [
      new box(true, false, false, false),
      new box(true,false, false, false),
      new box(true, false,true, false),
      new box(true,false, false, false),
      new box(true,false, true, false),
      new box(true,true, false, false),
      new box(true,false, false, true),
      new box(true,true, false, false),
      new box(true,false, false, true),
      new box(true,false, true, false),
      new box(true,false, true, false),
      new box(true,false, true, false),
      new box(true,true, false, false),
      new box(true,false, false, true),
      new box(true,false, false, false),
      new box(true,true, false, false),
      new box(true,false, true, true),
      new box(true,false, false, false),
      new box(true,false, true, false),
      new box(true,false, false, false),
      new box(true,false, true, false),
      new box(true,false, true, false),
      new box(true,true, false, false),
      new box(true,false, true, true),
      new box(true,true, false, false),
      new box(true,false, false, true),
      new box(true,true, true, false),
      new box(true,false, false, true),
      new box(true,false, true, false),
      new box(true,false, true, false),
    ],
    [
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, true, true, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      
    ],
    [
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, true, false, true),
    ],
    [
      new box(true, false, false, true),
      new box(false, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false,true, true, true),
      new box(false, false, true, true),
      new box(true, false, false, false),
      new box(false, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
    ],
    [
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, true, false, true),
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, false, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
    ],
    [
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, true, false),
      new box(false, true, false, true),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(false, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, false, false, false),
    ],
    [
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, false, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, true, true, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
    ],
    [
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, true, true),
    ],
    [
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
    ],
    [
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, true, false, false),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, true, true, false),
      new box(false, false, false, true),
      new box(true, true, false, false),
      new box(false, false, false, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
    ],
    [
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, false, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, false, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, false, true),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(false, true, false, false),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(false, false, true, false),
      new box(true, false, false, false),
      new box(true, true, false, false),
      
    ],
    [
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(false,false, true, true),
      new box(false,false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true,false, true),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(false, true, false, true),
    ],
    [
      new box(true,false, false, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, false, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, false, false),
    ],
    [
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false,false,false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
    ],
    [
      new box(true, false, false, true),
      new box(true, false, false, false),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false,false, false, false),
      new box(false, true, true, false),
      new box(false, true,false, true),
      new box(false,false, true, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true,false, true, false),
      new box(false, true, true,false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, true, true),
      new box(false, true, false,false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
    ],
    [
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, true, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, false,true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
    ],
    [
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, true, true, false),
      new box(true, false, false, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true,false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(false, true, false, true),
    ],
    [
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, false, false, false),
      new box(false, false, false, false),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false,true),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
    ],
    [
    new box(false, false, true, true),
    new box(true, true, false, false),
    new box(true, false, false, true),
    new box(true, false, true, false),
    new box(true, true, false, false),
    new box(true, false, true, true),
    new box(true, false, true, false),
    new box(true, true, false, false),
    new box(true, false, false, true),
    new box(false, true, true, false),
    new box(false, false, true, true),
    new box(true, true, false, false),
    new box(true, false, true, true),
    new box(true, false, true, false),
    new box(false, false, true, false),
    new box(true, true, true, false),
    new box(false, true, false, true),
    new box(true, false, true, true),
    new box(true, false, false, false),
    new box(false, true, true, false),
    new box(true, true, false, true),
    new box(true, false, false, true),
    new box(true, true, false, false),
    new box(false, true, false, true),
    new box(false, false, true, true),
    new box(true, false, true, false),
    new box(true, true, false, false),
    new box(false, true, false, true),
    new box(false, false, true, true),
    new box(true, false, false, false),
  ],
    [
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(false, true, false, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, true, false, true),
      new box(false, false, false, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, false, true, false),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
    ],
    [
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
    ],
    [
      new box(false, false, true, true),
      new box(true, false, false, false),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(false, true, false, false),
      new box(true, false, false, true),
      new box(false, true, false, false),
      new box(false, false, true, true),
      new box(false, true, false, false),
    ],
    [
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, false, false, false),
      new box(false, true, true, false),
      new box(false, false, false, true),
      new box(false, true, true, false),
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, true, false, false),
    ],
    [
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, true, false, false),
      new box(false, true, false, true),
      new box(false, false, true, true),
      new box(true, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(true, false, false, false),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
    ],
    [
      new box(false, true, false, true),
      new box(true, true, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(false, false, false, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, false, true, true),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, false, false, true),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(false, true, false, false),
      new box(true, true, false, true),
      new box(false, false, true, true),
      new box(false, true, false, false),
    ], 
    [
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(true, false, false, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, false, true, false),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, true, true, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(true, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, true, true, false),
    ], 
    [
      new box(true, false, false, true),
      new box(true, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(true, false, false, true),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, false, true, false),
      new box(false, false, false, false),
    ], 
    [
      new box(false, false, false, true),
      new box(true, false, true, false),
      new box(true, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(false, true, true, false),
      new box(false, false, true, true),
      new box(true, true, false, false),
      new box(true, true, false, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, true, true, true),
      new box(false, true, false, true),
      new box(true, false, false, true),
      new box(true, false, true, false),
      new box(true, true, false, false),
      new box(true, false, true, true),
      new box(false, true, false, false),
      new box(false, false, true, true),
      new box(true, false, true, false),
      new box(false, false, true, false),
      new box(true, true, false, false),
      new box(false, true, false, true),
      new box(false, false, false, true),
      new box(true, false, false, false),
      new box(true, true, false, false),
      new box(false, true, true, true),
  ],    
[
     new box(false, false, true, true),
     new box(true, false, false, false),
     new box(true, true, false, false),
     new box(true, true, false, true),
     new box(true, false, false, true),
     new box(true, true, false, false),
     new box(true, false, false, true),
     new box(true, false, true, false),
     new box(false, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(false, true, true, false),
     new box(false, true, false, true),
     new box(false, false, true, true),
     new box(true, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(true, true, true, false),
     new box(false, true, false, true),
     new box(true, true, false, true),
     new box(false, false, true, true),
     new box(true, false, true, false),
     new box(true, false, false, false),
     new box(true, false, false, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(false, true, true, false),
     new box(false, true, true, true),
     new box(false, false, false, true),
     new box(true, true, false, false),
 ],
 [
     new box(true, false, true, true),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(false, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(false, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, true, true, false),
     new box(false, false, true, true),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(true, false, true, false),
     new box(false, true, true, false),
     new box(false, false, true, true),
  ],
  ];
  Lost = false;
  isPaused = false;
  Won = false;
  distance = 0;
  constructor(initial, goal, timer) {
    this.person = new Point(initial.i, initial.j);
    this.initial = initial;
    this.goal = goal;
    this.timer = timer;
    this.prices = generatePricesList(this);
    this.enemies = generateEnemiesList(this);
    this.traps = generateTrapsList(this);
  }

  get eatenPricesNumber() {
    return this.prices.filter((price) => price.isEaten).length;
  }

  get eatenEnemeies() {
    return this.enemies.filter((enemy) => enemy.isEaten).length;
  }

  get score() {
    return (
      this.eatenPricesNumber * 3 +
      this.eatenEnemeies * -3 +
      this.timer / 10 +
      (this.distance == 0 ? 0 : Math.floor(100 / this.distance))
    );
  }
}

function generateRandomPoint(game, exceptions, isTrap = false) {
  let randomI = 0;
  let randomJ = 0;
  do {
    randomI = Math.floor(Math.random() * 30);
    randomJ = Math.floor(Math.random() * 30);
  } while (
    (randomI == game.person.i && randomJ == game.person.j) ||
    exceptions.findIndex(
      (exception) => exception.i == randomI && exception.j == randomJ
    ) != -1
  );
  if (isTrap) {
    return new Trap(randomI, randomJ);
  } else {
    return new Item(randomI, randomJ);
  }
}

function generatePricesList(game) {
  let valueList = [];
  return Array.from(Array(16), (_) => {
    let value = generateRandomPoint(game, valueList);
    valueList.push(value);
    return value;
  });
}

function generateEnemiesList(game) {
  let valueList = [];
  return Array.from(Array(8), (_) => {
    let value = generateRandomPoint(game, [...valueList, ...game.prices]);
    valueList.push(value);
    return value;
  });
}

function generateTrapsList(game) {
  let valueList = [];
  return Array.from(Array(10), (_) => {
    let value = generateRandomPoint(game,[...valueList, ...game.prices, ...game.enemies]
    );
    valueList.push(value);
    return value;
  });
}
